package saints

func saints() {
	june := map[int]string{
		1:  "St. Angela Merici",
		2:  "Sts. Peter, Erasmus, and Marcellinus, Martyrs",
		3:  "St. Kevin | St. Clothilde, Queen",
		4:  "St. Francis Caracciolo",
		5:  "St. Boniface, Martyr",
		6:  "St. Norbert | St. Philip, Deacon",
		7:  "St. Robert of Newminster",
		8:  "Sts. Medard and Gildard",
		9:  "St. Columkille | Sts. Primus and Felician, Martyrs",
		10: "St. Margaret of Scotland",
		11: "St. Barnabas, Apostle",
		12: "St. John of St. Facundo [us] | Sts. Basilides, Cyprinus, Nabor, and Nazarius, Martyrs",
		13: "St. Anthony of Padua",
		14: "St. Basil the Great",
		15: "St. Germaine | Sts. Vitus, Modestus, and Crescentia, Martyrs",
		16: "St. John Francis Regis",
		17: "St. Botolph | St. Ranier | St. Gregory Barbarigo",
		18: "St. Ephrem | Sts. Mark and Marcellianus, Martyrs",
		19: "St. Juliana Falconieri | Sts. Gervase and Protase",
		20: "Pope St. Silverius, Martyr",
		21: "St. Terence | St. Aloysius Gonzaga",
		22: "St. Paulinus of Nola",
		23: "St. Audrey | Vigil of the Birth of St. John the Baptist",
		24: "Birth of St. John the Baptist",
		25: "St. William, Abbot",
		26: "Sts. John and Paul, Martyrs",
		28: "Vigil of Sts. Peter and Paul | St. Irenaeus, Martyr",
		29: "Sts. Peter and Paul",
		30: "Commemoration of St. Paul | Seventeen Irish Martyrs",
	}

	july := map[int]string{
		1:  "Bl. Junipero Serra",
		2:  "Sts. Processus and Martinian, Martyrs",
		3:  "Pope St. Leo & St. Irenaeus",
		4:  "St. Theodore",
		5:  "St. Anthony May Zaccaria",
		6:  "St. John Fisher & St. Thomas More",
		7:  "Sts. Cyril and Methodius",
		8:  "St. Elizabeth of Portugal",
		9:  "St. Maria Goretti",
		10: "Holy Seven Brothers with Sts. Rufina and Secunda, Martyrs",
		11: "Pope St. Pius I, Martyr | St. Oliver Plunket",
		12: "St. John Gualbert | Sts. Nabor and Felix, Martyrs | St. Veronica of the Veil",
		13: "Pope St. Anacletus, Martyr | St. Mildred | St. Teresa of the Andes",
		14: "St. Bonaventure | St. Francis Solano | Bl. Kateri Tekakwitha",
		15: "St. Henry II, Emperor",
		16: "No Official Saint Today!",
		17: "St. Alexis the Beggar",
		18: "St. Symphorosa and Her Children, Martyrs & St. Camillus de Lellis",
		19: "St. Vincent de Paul",
		20: "St. Jerome Emilian",
		21: "St. Laurence of Brindisi & St. Praxedes",
		22: "St. Mary Magdalen",
		23: "St. Apollinaris of Ravenna & St. Liborius, Martyrs",
		24: "St. Christina",
		25: "Vigil of St. James the Greater, Apostle | St. James the Greater, Apostle | St. Christopher",
		26: "St. Anne",
		27: "St. Pantaleon, Martyr | Pope St. Celestine I",
		28: "Sts. Nazarius and Celsus, Victor I, and Innocent I, Martyrs",
		29: "St. Martha & 20: Sts. Felix II, Simplicius, Faustinus, Beatrice",
		30: "Sts. Abdon and Sennen | St. Ignatius of Loyola",
	}
}
